### ISSUE TITLE
Create a style_for_string_with_enum method

### ISSUE THREAD

**Issue by Peltoche** [sharkdp/lscolors#7]
Hi! 

I would like to use lscolors into my [lsd](https://github.com/Peltoche/lsd) project but the current implementation make it a little difficult to integrate. In its current state lsd generate a custom `Metadata` object from the file path and the file metadata then use it for the rendering. The advantages are that it separate the metadata parsing logic from the rendering and it consume the path and the metadata object only once. One of the downside is that we don't have the arguments required by lscolors (path and metadata) inside the rendering logic which make difficult to integrate.

I would like to propose you to create a new public method which could be useful. I would look like to: 
```rust
pub enum Filetype {
    Directory,
    Symlink,
    Executable,
    BrokenSymlink,
    Fifo,
    Socket,
    BlockDevice,
    CharDevice,
}

pub fn style_for_string_with_enum(&self, input: &str, filetype: FileType) -> Option<&Style> {}
```

What do you think of it?

**Comment by sharkdp** [comment]
Thank you very much for the feedback and sorry for the late response.

Before we add another public method to the API, I'd like to consider alternative options.

In your use case, instead of converting from `fs::Metadata` to `lsd::Metadata` to `lscolors::Filetype`, wouldn't it be easier (and faster) to just keep the original `fs::Metadata` object around (and call `LsColors::style_for_path_with_metadata`)?

If this is not possible for some reason, we could also think of using a trait (with methods such as `is_directory`) that would come with an implementation for `fs::Metadata`. You could then implement this trait for `lsd::Metadata`.

The third alternative is your `enum` version, which also sounds like a reasonable way to go (although I'd like to find another name for the function).

**Comment by Peltoche** [comment]
The first two solution seems a little complicated for us at the moment due to the `colorize` signature and our architecture in general:

 ```rust
pub fn colorize<'a>(&self, input: String, elem: &Elem) -> ColoredString<'a>

pub enum Elem {
    /// Node type
    File,
    SymLink,
   ...

    /// Permissions
    Read,
    Write,
   ...

    /// Last Time Modified
    DayOld,
   ...
}

```
The `Elem` enum allow us to keep the non color related logic outside the `color` package. For example we don't want to parse the last modified date and check if the file is older than 24H inside the color package. We can probably change the signature and add a `fs::Metadata` as argument but it would be only used when the LS_COLORS variable is set and I would not be very comfortable with this sort of optional variable.

The second solution would be more easy for us but still relatively hard as we would need to implement the trait for each value of the `Elem` enum (~25 elements).

In our case the third alternative seems to be the only viable solution between all the ones proposed. For the name, if you accept the proposition, you can choose what you want, the one above was only a quick proposition for the example.

**Comment by sharkdp** [comment]
@Peltoche Please take a look at #15 and see if this is something that could help with your use case. Please note that you will still be required to write some logic on your own if you don't want to use the `style_for_path`/`style_for_path_with_metadata` methods.

**Comment by sharkdp** [comment]
I'm going to close this (for now) as this seems to be resolved to me.

**Comment by Peltoche** [comment]
It seems all good! Thanks!
